# Generated by Django 3.2.9 on 2021-12-04 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('quantity_tickets', models.PositiveIntegerField(default=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('post_image', models.ImageField(blank=True, max_length=500, null=True, upload_to='concerts_images')),
            ],
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_voice', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpenAir',
            fields=[
                ('concert_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='concert.concert')),
                ('address', models.TextField()),
                ('headliner', models.CharField(max_length=64)),
            ],
            bases=('concert.concert',),
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('concert_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='concert.concert')),
                ('age', models.PositiveIntegerField()),
            ],
            bases=('concert.concert',),
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_items_on_basket', models.PositiveIntegerField(default=0)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concert.concert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassicalMusic',
            fields=[
                ('concert_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='concert.concert')),
                ('name_executor', models.CharField(max_length=64, unique=True)),
                ('type_of_voice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concert.voice')),
            ],
            bases=('concert.concert',),
        ),
    ]
