# Generated by Django 3.2.9 on 2021-12-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classicalmusic',
            name='type_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='openair',
            name='type_id',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='party',
            name='type_id',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
